spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: zrq1351
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true  #日志中显示sql语句
  application:
    name: linkage
  thymeleaf:
    encoding: UTF-8 # 模板编码
    prefix: classpath:/public/  # 页面映射路径
  cache:
    ehcache:
      config: 'classpath:ehcache.xml'
server:
  port: 8080 #端口号
